
spring.application.name=backend

spring.datasource.url=jdbc:mysql://mysql-f3bdd36-edushield.a.aivencloud.com:20873/edushield_db?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=edushield-super-secret-key-change-this-later-make-it-long-enough-for-hs256
jwt.expiration=86400000
# Server port
server.port=8081